GET http://localhost:8080/api/trainingSession
Accept: application/json

###

GET http://localhost:8080/api/trainingSession/1
Accept: application/json

###

GET http://localhost:8080/api/trainingSession?id=1
Accept: application/json

###
